
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Tokens {
  /* terminals */
  public static final int div = 5;
  public static final int puntocoma = 8;
  public static final int pareni = 7;
  public static final int num = 9;
  public static final int EOF = 0;
  public static final int menos = 3;
  public static final int parend = 6;
  public static final int error = 1;
  public static final int por = 4;
  public static final int mas = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "mas",
  "menos",
  "por",
  "div",
  "parend",
  "pareni",
  "puntocoma",
  "num"
  };
}

